// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07/09/2026, 15:27:14
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/rafael.luz/Documentos/projetos/daluzz-studio/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/rafael.luz/Documentos/projetos/daluzz-studio/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/rafael.luz/Documentos/projetos/daluzz-studio/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/rafael.luz/Documentos/projetos/daluzz-studio/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/rafael.luz/Documentos/projetos/daluzz-studio/plugins/**/*.{js,ts,mjs}","/home/rafael.luz/Documentos/projetos/daluzz-studio/composables/**/*.{js,ts,mjs}","/home/rafael.luz/Documentos/projetos/daluzz-studio/utils/**/*.{js,ts,mjs}","/home/rafael.luz/Documentos/projetos/daluzz-studio/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/rafael.luz/Documentos/projetos/daluzz-studio/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/rafael.luz/Documentos/projetos/daluzz-studio/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;